# Numpy Indexing and Selection

In [1]:
import numpy as np

In [4]:
arr=np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
arr[8]

8

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [14]:
arr[0:5]=100

In [15]:
arr # broadcasts elements

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
slice_of_arr=arr[0:6]

In [17]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [18]:
slice_of_arr[:]='Suhas'

ValueError: invalid literal for int() with base 10: 'Suhas'

In [19]:
slice_of_arr[:]=99

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr_copy=arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:]=100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Matrix

In [26]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#double bracket format

arr_2d[0][0]

5

In [29]:
arr_2d[2][0]

35

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
#single bracket 

arr_2d[2,0]

35

In [32]:
arr_2d[1,1]

25

In [33]:
arr_2d[1][1]

25

In [35]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr_2d[1:,2]

array([30, 45])

In [43]:
arr_2d[1:,2]

array([30, 45])

In [44]:
arr_2d[1:,2].reshape(2,1)

array([[30],
       [45]])

# Conditional Selection

In [45]:
arr=np.arange(1,11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr > 5 #array of boolean values

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
bool_arr=arr > 5

In [49]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr] #only true value

array([ 6,  7,  8,  9, 10])

In [52]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [54]:
arr[arr<3]

array([1, 2])

In [55]:
arr<3

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [56]:
arr_2d=np.arange(50).reshape(5,10)

In [57]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
arr_2d[1:4,1:4] #lil different than python its +1

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [61]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])