# Numpy_Arrays

1D or 2D

In [ ]:
my_list=[1,2,3]

In [4]:
print(my_list)

[1, 2, 3]


In [5]:
import numpy as np

In [7]:
arr=np.array(my_list)

In [8]:
print(arr)

[1 2 3]


In [9]:
my_mat=[[1,2,3],[4,5,6],[6,7,8]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
ar=np.array(my_mat)
print(ar)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [12]:
np.arange(0,10) # range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2) # range function with step 2

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((3,3)) #2D has 2 brackets

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones((3,3,3))#3D has 3 brackets

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [29]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.rand(5) #random value from 0 to 1

array([0.92814727, 0.18003803, 0.74298196, 0.6489568 , 0.9557499 ])

In [33]:
np.random.rand(5)

array([0.28967955, 0.08454734, 0.38318664, 0.60523667, 0.68746643])

In [34]:
np.random.rand(5,5)

array([[0.36208577, 0.70686772, 0.12544649, 0.40425892, 0.06175761],
       [0.86804812, 0.79239148, 0.74511758, 0.84758787, 0.24831598],
       [0.11537195, 0.74256652, 0.58263604, 0.28484506, 0.48341941],
       [0.38684877, 0.11124704, 0.35195271, 0.98601364, 0.03892937],
       [0.95016291, 0.07234977, 0.61831856, 0.52578725, 0.79311933]])

In [35]:
np.random.randn(2)

array([0.39132025, 1.14758306])

In [37]:
np.random.randn(2)

array([-0.35158591, -0.77122661])

In [38]:
np.random.randn(4,4)

array([[-0.01305918,  0.12392212,  0.24154517, -1.12709959],
       [ 2.15959984, -0.06537545, -0.85841168,  0.32173551],
       [-0.27782509,  1.22897888,  1.05021153,  0.82632803],
       [-0.0410605 ,  1.63411933, -1.47032948, -0.42161146]])

In [39]:
np.random.randn(4,4)

array([[ 0.22763041, -2.1246717 , -1.11125746,  0.1666324 ],
       [-0.93417916, -0.08282576, -0.38730305,  0.97845868],
       [ 0.58999135,  1.58851162, -1.14813004, -1.67147999],
       [ 1.88310939, -0.07061897, -1.3057824 ,  0.77715458]])

In [41]:
np.random.randint(1,100) #random int btw 1 and 100

87

In [42]:
np.random.randint(1,100) #random int btw 1 and 100

23

In [43]:
np.random.randint(1,100, 10) #10 random integers

array([67, 53, 12, 28, 82, 20, 87, 30, 29, 73])

In [44]:
np.random.randint(1,100, 10) #10 random integers

array([19, 73, 75, 88, 63, 18, 27, 32, 46, 72])

In [45]:
arr=np.arange(25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
ranarr=np.random.randint(0,50,10)

In [49]:
ranarr

array([22, 14, 14, 31, 31, 41, 38, 16,  8,  8])

# Reshape

In [51]:
arr.reshape(5,5) # fill array in order

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.reshape(5,10) # not possible as 5*10 is 50 but arr has only 25 values

ValueError: cannot reshape array of size 25 into shape (5,10)

In [58]:
ranarr

array([22, 14, 14, 31, 31, 41, 38, 16,  8,  8])

In [59]:
ranarr.max() # max value

41

In [61]:
ranarr.min() # min value

8

In [63]:
ranarr.argmax() # index position of max value

5

In [65]:
ranarr.argmin() # index position of min value

8

In [66]:
arr.shape # 1D vector

(25,)

In [77]:
ar=arr.reshape(5,5)
print(ar)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [79]:
ar.shape # 2D

(5, 5)

In [83]:
arr.dtype

dtype('int32')

In [86]:
from numpy.random import randint as rd # aliasing

In [87]:
rd(2,10)

3